name: 'omni_revenue_transform'
version: '1.0.0'
config-version: 2

profile: 'omni_revenue'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  omni_revenue_transform:
    staging:
      +schema: analytics_mart
      +materialized: table
